* Capture the flag(CTF)
	+ [Commonly Used Tools](tools)
	+ [Web](web)
	+ [Cryptography](Cryptography)
	+ [Forensics](forensics)
* Making a boot2root VM
	+ [Important rules](rules)
	+ [General things](Make-boot2root-VM)
	+ [Setting Systemd services](services)
	+ [Setting fail2ban](fail2ban)
* BugBounty notes for **Android**
	+ [General](Android)
	+ [Adb/drozer commands](Commands)
	+ [Intents](Intents)
	+ [Permissions](Permissions)
	+ [Activities](Activities)
	+ [Broadcast Receivers](Broadcast_Receivers)
	+ [Content Providers](Content_Providers)
	+ [Services](Services)
* BugBounty notes for **WEB**
	+ [Authentication](Authentication)
	+ [CORS](CORS)
	+ [General Web](General)
	+ [HTTP Parameter poisoning](HTTP-Parameter-poisoning)
	+ [IDOR](IDOR)
	+ [graphql](graphql)
* [Starting with (n)vim](Learning-Vim)
* [Bluetooth](bluetooth)(nothing big)
* [Hacking boot2root/ OSCP notes](boot2root)
